/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { RefObject, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["12"]: THREE.Mesh;
    ["11"]: THREE.Mesh;
    ["10"]: THREE.Mesh;
    ["9"]: THREE.Mesh;
    ["8"]: THREE.Mesh;
    ["7"]: THREE.Mesh;
    ["6"]: THREE.Mesh;
    ["5"]: THREE.Mesh;
    ["4"]: THREE.Mesh;
    ["3"]: THREE.Mesh;
    ["2"]: THREE.Mesh;
    ["1"]: THREE.Mesh;
    Cylinder027: THREE.Mesh;
    Cylinder027_1: THREE.Mesh;
    Cylinder027_2: THREE.Mesh;
    Cylinder027_3: THREE.Mesh;
    Cylinder027_4: THREE.Mesh;
    Cylinder027_5: THREE.Mesh;
    Cylinder027_6: THREE.Mesh;
    Cylinder027_7: THREE.Mesh;
  };
  materials: {
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshPhysicalMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshPhysicalMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
  };
};

export function Model(
  props: JSX.IntrinsicElements["group"] & {
    modelRef?: RefObject<THREE.Group>;
    material?: THREE.Material;
  },
) {
  const material = props.material;
  const { nodes, materials } = useGLTF(
    "/assets/obj/clock_joined.glb",
  ) as GLTFResult;
  return (
    <group {...props} ref={props.modelRef} dispose={null}>
      <group name="Scene">
        <mesh
          name="12"
          castShadow
          receiveShadow
          geometry={nodes["12"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.076, 1.264, 0.146]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="11"
          castShadow
          receiveShadow
          geometry={nodes["11"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.357, 1.191, 0.156]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="10"
          castShadow
          receiveShadow
          geometry={nodes["10"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.551, 1.006, 0.183]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="9"
          castShadow
          receiveShadow
          geometry={nodes["9"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.586, 0.738, 0.222]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="8"
          castShadow
          receiveShadow
          geometry={nodes["8"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.516, 0.468, 0.261]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="7"
          castShadow
          receiveShadow
          geometry={nodes["7"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.311, 0.271, 0.29]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="6"
          castShadow
          receiveShadow
          geometry={nodes["6"].geometry}
          material={material ?? materials["Material.009"]}
          position={[-0.044, 0.19, 0.302]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="5"
          castShadow
          receiveShadow
          geometry={nodes["5"].geometry}
          material={material ?? materials["Material.009"]}
          position={[0.239, 0.271, 0.29]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="4"
          castShadow
          receiveShadow
          geometry={nodes["4"].geometry}
          material={material ?? materials["Material.009"]}
          position={[0.432, 0.465, 0.262]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="3"
          castShadow
          receiveShadow
          geometry={nodes["3"].geometry}
          material={material ?? materials["Material.009"]}
          position={[0.501, 0.738, 0.222]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="2"
          castShadow
          receiveShadow
          geometry={nodes["2"].geometry}
          material={material ?? materials["Material.009"]}
          position={[0.435, 1.009, 0.183]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <mesh
          name="1"
          castShadow
          receiveShadow
          geometry={nodes["1"].geometry}
          material={material ?? materials["Material.009"]}
          position={[0.231, 1.193, 0.156]}
          rotation={[1.426, 0, 0]}
          scale={0.192}
        />
        <group
          name="Cylinder011"
          position={[0.458, 2.313, -0.111]}
          rotation={[1.426, 0, Math.PI / 2]}
          scale={[0.027, 0.454, 0.027]}
        >
          <mesh
            name="Cylinder027"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027.geometry}
            material={material ?? materials["Material.001"]}
          />
          <mesh
            name="Cylinder027_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_1.geometry}
            material={material ?? materials["Material.010"]}
          />
          <mesh
            name="Cylinder027_2"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_2.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cylinder027_3"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_3.geometry}
            material={material ?? materials["Material.003"]}
          />
          <mesh
            name="Cylinder027_4"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_4.geometry}
            material={material ?? materials["Material.006"]}
          />
          <mesh
            name="Cylinder027_5"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_5.geometry}
            material={material ?? materials["Material.007"]}
          />
          <mesh
            name="Cylinder027_6"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_6.geometry}
            material={material ?? materials["Material.005"]}
          />
          <mesh
            name="Cylinder027_7"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder027_7.geometry}
            material={material ?? materials["Material.011"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/obj/clock_joined.glb");
